### ISSUE TITLE
provided "value" property is invalid" is raised when trying to update value and max = 1

### ISSUE THREAD

**Issue by superseby2** [mskocik/svelecte#145]
Hello, 

When my "value" variable which is binded to Svelecte value prop is updated I always get  

 "value" property is invalid"  no matter

Here is the REPL : 

https://svelte.dev/repl/e7da4dfe759e49608c0f905dab35e07b?version=3.52.0

The "funny" thing is that I've been using bind value to update my Svelete components and everything used to work till I have upgraded to Sveltekit 1.0 (which brought with many other stuff svelte version 3.55.0). But, downgrading svelete to 3.52.0 (which was the version I was using) did not make the bug go away and just to make the mystery thicker I can reproduce on REPL.

So I do not why everything used to work, but I can confirm it does not with multiple version svelte 3.52 -> 3.55 and svelecte 3.9.0 (the version I was in)
I have this strange feeling I am not doing something right; please let me know. Any help highly appreciated !

thx !

**Comment by superseby2** [comment]
Update : 

I have tracked down the pb until 

```
385   function selectOption(opt) {                                                                                          
386     if (!opt || (multiple && maxReached)) return false;
```
It seems like maxReached is true. As if  somehow the length of current selection is not updated (or updated after ?) when the evaluation occurs ...

**Comment by mskocik** [comment]
When I update the `value` assignment, it works ok:

[update REPL](https://svelte.dev/repl/1ebf0a2c0f5d4c51b2f2e844a7753b9e?version=3.52.0)

**Comment by superseby2** [comment]
I think I am going crazy as I was actually updating my REPL and could not reproduce neither .. 

I retry from scratch and see if I could reproduce.. 

Thanks for your quick reply

**Comment by superseby2** [comment]
Okay .. not completely crazy (yet)

Here is the RPL update 


https://svelte.dev/repl/e7da4dfe759e49608c0f905dab35e07b?version=3.55.0

when max is passed as Number the exception is raised.
Passed as string all is good.

**Comment by mskocik** [comment]
Thanks for reporting. I also fix when string is passed to `max`. (It really didn't work with string, bevause it allowed you to select more items than max)

**Comment by superseby2** [comment]
Thanks for fixing so fast! 

Now that I have upgraded to 3.13.1 I do have a "side-effect" 

When value is updated I've got 'property is invalid"  while options is not filled-in. I pinpoint this is happening since version 3.10.1

I could reproduce in the REPL : 

https://svelte.dev/repl/e7da4dfe759e49608c0f905dab35e07b?version=3.55.0

**Comment by mskocik** [comment]
Yes, it was possible before, but it was definitely a bug. Because you were allowed to set value, which was outside option list. But initially I kept both funcionalities, but it turned out, it was mess to keep up, so I threw it away (issue #128) .

But regarding to your REPL this **should be** possible to set value outside of options list:

```svelte
value = {"$id": "python2", label_en: "Python", label_fr: "Python", color: "#b5cbbb", $created: true}  
//                                                      adding `$created` internal param ^

<Svelecte creatable bind:value></Svelecte>
```

...but it doesn't work at the moment... should be easy to fix

**Comment by mskocik** [comment]
@superseby2 updated (working) [REPL](https://svelte.dev/repl/f6025119a3e54417a49f953456c13455?version=3.55.0) with the latest version

**Comment by superseby2** [comment]
Thanks again ! And yes it is working fine.  
In the meantime, I found the real problem that was bugging me.  It feels like it is more of a reactivity hell/issue. But I will share with you just in case this makes sense to you more than I ...

To summarize : when using a fetch which is a function with a parameter that changes during reactivity, Svelecte will throw an the Invalid exception (while the value itself is the exact same)

https://svelte.dev/repl/faa59222a28a4c12bbb2d55a7e51eeaf?version=3.55.0
All you need to do in the REPL is update the input text value and check the exception in the console.


My solution : "capture" the parameter to make sure it is not  get updated somehow and does not bugger Svelecte.

**Comment by mskocik** [comment]
Your example seemed really strange to me on the first sight, but I understood your intention 😆

There are 2 ways how to handle it:

1. you use `$created` prop on your init values (you are using `creatable` and `valueAsObject`) as added in `v3.13.2`
2. rewrite your async function like this: [REPL](https://svelte.dev/repl/d99ce610f4ea494488aa86a799dd5f44?version=3.55.0) 

But to the point of your problem: Svelte updates the object, because it's property is being updated. Therefore it updates Svelecte's value. And BECAUSE your value is **outside** of option list (which is empty), selection is cleared.

Setting value _without_ `options` property is allowed only during component initialization. Afterwards you need to use proposed solution no. 1.
