### ISSUE TITLE
Advice for building term value (two part) autocompletion

### ISSUE THREAD

**Issue by niemyjski** [mskocik/svelecte#199]
I was looking at this library and trying to see the best way to build something that would allow me to easily autocomplete Lucene style terms (a left side (term) and then the value dynamically).

Let's say I have two fields. 

1. `status` with values `open` or `closed`
2. `ip` and a user can enter in any value or get resolved by a async terms query.

What would be the best way to start auto completing the known term list (status and ip) but then allow either auto completion on the right side either dynamic or static?

![image](https://github.com/mskocik/svelecte/assets/1020579/ffafa513-3020-44fc-aa59-911298983c5e)

This is very close to what I was thinking: https://github.com/vectordotdev/react-query-assist

**Comment by mskocik** [comment]
You mean something like this [REPL](https://svelte.dev/repl/8a2e80566c7c410f8bcdc859a52530b8?version=4.2.1)? 

I am not sure it is possible to combine async and pre-defined options (for `ip`). Because async always overwrite `options` property, even when empty list.

You can make it work by using async options only - meaning for all steps you define `fetch` url (without custom `[query]` param), so they will be fetched immediately. Not sure this is the best component for your use case

**Comment by niemyjski** [comment]
Kind of, but closer to that query assist. I basically have static known terms and values (see https://exceptionless.com/docs/filtering-and-searching/#searchable-fields-and-requirements) which I could auto complete, and others I would need to do a terms aggregation

**Comment by mskocik** [comment]
I am getting errors, when I want to build something like that, I will look into it. But I don't promise it will be possible after the fix anyway. It's kind of specific use case which Svelecte maybe can't satisfy. Will be wiser, when I fix it
