### ISSUE TITLE
only show  "Add with CTRL+Enter" only when there is no options to select from  + cursor with single select

### ISSUE THREAD

**Issue by GamalTawaf** [mskocik/svelecte#260]
First, Thanks for the amazing library :) 
I have two issues: 
1. The issue is basically the same as mentioned here: https://github.com/mskocik/svelecte/issues/86. [REPL](https://svelte.dev/playground/1bc1743019e84630801546b2fe618db3?version=5.1.3)
2. the second one is when user selects one item we still see the cursor telling the user they can select another but I do not have multiple 
here is a demo of what I mean: I was allowed to add "test" even though it is part of the options 

![svelecte-issue-repl](https://github.com/user-attachments/assets/2cd0cb6d-f09f-4086-a0ce-871f869ea61e)

Env: 
```

    "svelecte": "^4.4.0",
    "svelte": "^4.0.5",

```

**Comment by mskocik** [comment]
> I have two issues:

1) this cannot be done. You can't guarantee that user wouldn't want to insert some "substring" of available options. Take your example: If you would want to insert `est` it wouldn't be possible.
2) is valid bug, but you should be using `createFilter` differently. I understand that docs are misleading (description of `createFilter` is still in v3 format). Your `createFilter` function should return `true` if you want to _prevent_ item creation. Will be fixed soon.

**Comment by mskocik** [comment]
Now fixed in `v4.4.1` and here is your [REPL](https://svelte.dev/playground/1bc1743019e84630801546b2fe618db3?version=4.2.0#H4sIAAAAAAAACm1SwW7CMAz9FS8XQGIwYKeOIE3TkHabxJFyCMXQiJBGiQubov77ktIyVHFoKj8_P9sv8UyLE7KEuTMqzAhBOleiY0O2lyr8k7Vn9GsiJQIBbwrejRnFIorYVjh8hGeFJtQUZNjcZVYaWqQ6JXkyhSVYtT33tjhBrx2hFykKCQpDstAOOKwjlBL4s1AlJjAZghJbVAmkjNBRyqphhzLtUGDygDTrkqbwgPXaZc1aEtTHph245sdgX-oszg7BM0L7YVEQ9jVevghPA_DXBhaptLpdc3Tl9vvXeAB80aRGdXfgnEMrMVKoD5TDU8Be3qJcler5-N9jPW_djUnf9KhikCnhHE9vV_5shA2XlLI6GUcVW4Xcky2xLjgimusKO-73QjlsdFDYDlUoVVw-d5KkPtzBW6l3yc2dXB5yFT5aSuso7nMv64Jqln_bwjjuPbijNKvwWhKIalBVtylxWRsWau9MrmAc1g9Pj_CHWFJPsKn-ABkqCo_nAgAA) fixed (slightly updated `filterCreate` function)
