### ISSUE TITLE
problem in "multiple-mode" with shared option-array

### ISSUE THREAD

**Issue by berohndo** [mskocik/svelecte#32]
**First of all I would like to thank you for your great work.**

Then I would like to mention a behavior of the component that I suspect is a bug.

For example, if you run 2 instances of svelecte in "multiple" mode, with the same options array, then they interfere with each other, because svelecte also uses the options array to manage the state (isSelected true/false).

I created a small show case in my repo:

[Minimal svelte project](https://github.com/one-phalanx/svelecte-issues)

Would be great if you could take a look at it.
Thanks and best regards
Bernd

**Comment by mskocik** [comment]
I am aware of this, but I don't think it's a bug. As you can see in [docs dataset file](https://github.com/mskocik/svelecte-docs/blob/main/src/data.js) options are returned from function to ensure they are unique to each Svelecte instance.

The only way to fix this would be to duplicate options aray inside Svelecte, which is not desirable, because I would like to avoid unnecessary work of creating new objects if not needed. If you need it (like in your case), you need to handle it on your side. Like you do in your non-shared examples or by any other technique used for creating real array clone.

If you think this is really a bug and should be fixed, try to convince me. In the meantime I am closing it.

**Comment by mskocik** [comment]
I am going to do some internal changes for upcoming version and this should be taken into account as well. Basically options array should not be mutated in any way.
