### ISSUE TITLE
Svelecte does not update when bound value changes

### ISSUE THREAD

**Issue by jieter** [mskocik/svelecte#41]
Not sure if the title is exact enough, but while implementing a paginated form, Svelecte does not change when the bound value updates, while regular inputs do. 

Pressing the button in the example below does not update the selected value in the Svelecte component, but does update the selected value in the text input.

[Svelte repl](https://svelte.dev/repl/fde75055c1914adaba10787246bfad44?version=3.44.0)
```
<script>
import Svelecte from 'svelecte';
const options = [{id: 1, value: 'a'}, {id: 2, value: 'b'}, {id: 3, value: 'c'}, {id: 4, value: 'd'}];
	
let value = 1;
let text = 'bar';
</script>

<Svelecte {options} bind:value={value} valueField="id" />
<input type="text" bind:value={text} />
<hr>

<button on:click={() => {value = 2; text = 'foo';}}>
	Change value + text
</button>

value: {value}
text: {text}
```

**Comment by mskocik** [comment]
I know about this and it's intentional. Actually I was thinking about mentioning in documentation that `value` is not reactive and it never was.

The thing is - `selection` is reactive and `value` is _derived_ from current selection. There can't be 2 different properties controlling inner selection. I updated your [REPL ](https://svelte.dev/repl/1c3840d3f6764e84bb7f7f9c6efa61a9?version=3.44.0) to work as expected. I admit it can be a little confusing, because you _can_ set inner selection by `value` on component initialization.

I am open to suggestions how to handle this. If there should be a "switch", which would determine, which _value property_ (`value` or `selection`) should be handled?

**Comment by jieter** [comment]
Thanks for explaining the dilemma.

What's the best solution is going to dependent on your point of view using the component. My expectation was that I could use `<Svelecte options bind:value />` as a drop-in replacement for `<select bind:value>{#each options as option}<option value={option.value}> ....`.

I think the current situation is too confusing and one of `value` / `selection` should be exposed as property, with some clearly documented way of accessing the other, like an event handler. But you might have different goals in mind.

**Comment by mskocik** [comment]
My goal was to have it flexible 😄 but the truth is, that selection is accessible through `change` event, or through `getSelection` method. Which is documented, but it's not clear. So possibly it would be enough to keep `value` reactive.

When I checked packages using Svelecte, all three are using `bind:value`. Will have to think more about this, because I would like to keep both ways 🤔

**Comment by mskocik** [comment]
Okay, I tried to fix it, but it's impossible to have 2 properties where one affects the second one.

<del>
I am going to combine them together! It means no matter what value will `value` property have (whether real _value_ or selection object(s)), Svelecte will do some conversions internally and still return proper value. It means, the `selection` property will be removed and replaced by "always returning `Object` or `Object[]`" property `readValue`</del> Reworked in totally different way

**Comment by mskocik** [comment]
Okay, try now, `value` should be reactive as expected and by default it expects `valueField` property values. Check release page for breaking changes and if they affect you.

**Comment by jieter** [comment]
I'm experimenting with 3.0.0, I noticed `valueAsObject` is not yet documented.

What should I expect as `item` in `renderer` after updating `bind:value`? 

What I see is `{0: 'VOLVO%20OPEN%2070', 1: '*VOLVO OPEN 70', $created: true}`, is this due to Svelecte expecting a list of objects instead of the list of lists I use?

REPL: https://svelte.dev/repl/b51e4d772e9f4451a9342ffa86833ec1?version=3.44.0

**Comment by jieter** [comment]
To answer my own question: this seems to be the case, If I transform the list of lists to a list of dicts, it works as expected.

Upgrade commit: https://github.com/jieter/orc-data/commit/e01b78dd5e5f3025631e7ffe3d201023237b320f. In this case, the new API needs much less glue code.

**Comment by mskocik** [comment]
> I'm experimenting with 3.0.0, I noticed `valueAsObject` is not yet documented.
> 

It's documented on multiple occasions, because it's scattered all around the docs 😁 One mention is in readme.md itself, once in docs and once in release notes. But I admit that documentation probably isn't written in the most user-friendly way. Probably reworking the docs completely would help, but it's quite hard, when I have no feedback from third person and you know... creator's blindness 😃.
 
> What I see is `{0: 'VOLVO%20OPEN%2070', 1: '*VOLVO OPEN 70', $created: true}`, is this due to Svelecte expecting a list of objects instead of the list of lists I use?

And to answer this question: Svelte internally works with objects. But `options` can be array (list) of objects _OR_ plain array (array of strings typically). When plain array is provided, it is converted internally to array of objects with default properties (`value` - which will have value of item index in array, `label` - array item itself)

**Comment by jieter** [comment]
> > I'm experimenting with 3.0.0, I noticed `valueAsObject` is not yet documented.
> 
> It's documented on multiple occasions, because it's scattered all around the docs 

Searching for `valueAsObject` on the page yields no results, but you are right that it's there in 'exposed selection properties' of 'basic usage'.

<img width="1088" alt="Screenshot 2021-11-01 at 08 10 10" src="https://user-images.githubusercontent.com/1470389/139634797-f84aa40f-2c40-4f13-9a4a-99182455b703.png">

**Comment by mskocik** [comment]
Yes, you're right, it's missing from main option list, didn't notice that 😮
