### ISSUE TITLE
__vite_ssr_import_7__.registerSvelecte is not a function

### ISSUE THREAD

**Issue by abushak** [mskocik/svelecte#44]
Sveltekit ("@sveltejs/kit": version": "1.0.0-next.186", "vite": "^2.6.10" ) 

it succsesfuly runing 1-st try "npm run dev" with trowing error only in console:
"__vite_ssr_import_7__.registerSvelecte is not a function

after reload - page shows up with error..

Iam trying to do ["Wired (dependent) selects " ](https://mskocik.github.io/svelecte/#dependent-selects)

**Comment by mskocik** [comment]
`registerSvelecte` is meant to be used _in the browser_, which calls [`customElements.define`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define) under the hood. If you want to build dependent selects in svelte/sveltekit app, you need to do you by yourself.

It the documentation it works, because `registerSvelecte` is called on the client. Not on the server.

**Comment by mskocik** [comment]
@abushak can this issue be closed?

**Comment by abushak** [comment]
> @abushak can this issue be closed?

yes
