### ISSUE TITLE
Feature Request: add option to use svelte component as item renderer.

### ISSUE THREAD

**Issue by codeho** [mskocik/svelecte#54]
Hi,

It would be great if it'd be possible to give the 'renderer' option a svelte component as parameter
instead of having to have a function with backtick syntax.

**Comment by mskocik** [comment]
So you suggest possibility to replace whole `Item` component or just _its_ inner content?

**Comment by codeho** [comment]
Well, in order to keep consistency with the Actions etc. it might be a good idea to add a 
component prop to Item.svelte and if its set load that component within `<div class="sv-item">` instead of the @html block.

On the other hand it could get a little messy with all the isGroupheader and the "isSelected" and "deselect", so maybe having the option to override the whole thing, and then the dev needs to take care of his own isSelected highlight and click actions, would also be something to consider.

I kinda like how svelte-select solved this by having a Item Component that can just be overridden and solve the 'isSelected' situation just via css classes as props.

**Comment by mskocik** [comment]
The thing is, Svelecte is doing a lot of things under the hood. And it only gets complicated with multiselection and option groups (because `Item.svelte`  is used in dropdown and also renders selected items). 

`Svelte-select` use mentioned `Item` property only in dropdown and use it's default for selected items. While Svelecte gives you full control also over appearance of selected items. Have you seen [custom rendering example](https://mskocik.github.io/svelecte/#item-rendering)?

---

> the option to override the whole thing, and then the dev needs to take care of his own isSelected highlight and click actions,

Yes, and the question is, if it's worth doing it in the first place. Imagine you need to do this 6 times for different renderers. Not fun from my point of view.

Would require more thinking about the right approach. You can try as well if you have some idea. I am responsive to PRs.

**Comment by codeho** [comment]
yes, i understand. of course i've seen the custom rendering example :) it's a cool solution and i like it, but like i said, i'm not too hot on the backtick html idea, and would love to have it accept components as well.
Maybe it would make sense to have the possibility to add resultItemComponent and ControlItemComponent. 
so they can, if needed, be displayed separately.
i'll grab a fork and play around with it a little bit. Thanks for considering this :)

**Comment by mskocik** [comment]
I found some time to do it, felt really creative today 🤣 There is small piece of information in the docs, should be doable based on it 👍
