### ISSUE TITLE
Issues with HTML sanitization (?)

### ISSUE THREAD

**Issue by knajjars** [mskocik/svelecte#78]
When the labelField has some HTML, for example: `"><img src=x onerror=alert(1)>` and you open the dropdown with Svelecte, you will see the alert popup. 
<img width="447" alt="Screen Shot 2022-01-07 at 9 04 40 AM" src="https://user-images.githubusercontent.com/19353218/148562949-14fc632c-3d1c-4197-ae49-49bb3b9e52f1.png">

**Comment by mskocik** [comment]
I see no point in doing this on library level. Because you are in control what data you pass to Svelecte in `options` prop. Typically you should pass data only, and format them visually by providing custom `renderer`. So you can sanitize item HTML with your own `renderer`.

Or if you enable user to insert new items (through `creatable` prop), you can do sanitization through your own `createFilter` function.

Here is an [example](https://svelte.dev/repl/1a0f9f775aab44baa2bac790c663b44c?version=3.45.0) of sanitization through `renderer` prop.
